apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: martinalarame/api_nodejs:v1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: API_KEY
              value: 2f5ae96c-b558-4c7b-a590-a501ae1c3f6c
            - name: JWT_SECRET
              value: mi-secreto-para-jwt
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
